# Generated by Django 4.0.1 on 2022-01-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_registeredcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredcourse',
            name='user',
        ),
    ]
