# Generated by Django 4.0.1 on 2022-01-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_registeredcourse_userprof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisteredCourse',
        ),
    ]
