# Generated by Django 4.0.1 on 2022-01-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_registercourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterCourse',
        ),
    ]
