# Generated by Django 4.0.1 on 2022-01-27 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseAbbrivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_abbr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LectureLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lec_num', models.IntegerField()),
                ('lec_date_time', models.DateTimeField(auto_now_add=True)),
                ('lec_link', models.URLField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_abbriv',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.courseabbrivation'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.branch'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_year',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.year'),
        ),
    ]
